apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    component: db
spec:
  containers:
    - name: postgres
      image: durgasingh/postgres12:latest
      ports:
       - containerPort: 5432
